### ISSUE TITLE
Lichess PGN download fails

### ISSUE THREAD

**Issue by michael-denzler** [Simske/pgn-downloader#15]
Download of lichess games seems to stop to work in v 0.2.2:

```
# pgn-downloader lichess ChessUser
pgn-downloader 0.2.2
Downloading games for user 'ChessUser' from lichess
Filters:
    Color: both
    Date: since Account creation until now
    Modes: blitz, rapid, classical, correspondence
Downloading: 0 games [00:00, ? games/s]

An Error occured:
Response ended prematurely
```

Download of chess.com games is still working.
